### ISSUE TITLE
Creating a similar package

### ISSUE THREAD

**Issue by kungpaogao** [lucaslcode/outline_material_icons#1]
Hey Lucas,

I appreciate the work you've done. I am trying to create a similar package with the other types of Material icons. Could you explain how you went about making your .dart file? I could probably create something similar using quite a bit of manual work (find and replace), but I was wondering if you used a more efficient process.

Thanks,
Andrew :)

**Comment by lucaslcode** [comment]
Hi, my apologies that I missed this one!
It was a while ago that I did this, but my process was something along these lines:
-Scrape all the svg image files from the google material icons website, also scrape all the names
-use icomoon to generate a ttf from the svgs
-use a bunch of regex on the list of names to create the dart file.

Best of luck!
